apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo1
  labels:
    app: microservice-demo1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-demo1
      type: api
  template:
    metadata:
      labels:
        app: microservice-demo1
        type: api
    spec:
      containers:
      - name: microservice-demo1
        image: microservice-demo1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo2
  labels:
    app: microservice-demo2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-demo2
      type: api
  template:
    metadata:
      labels:
        app: microservice-demo2
        type: api
    spec:
      containers:
        - name: microservice-demo2
          image: microservice-demo2
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: open-telemetry-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: microservice-demo1
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-demo2-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: microservice-demo2